### 채널 생성
POST http://localhost:3000/packaging/channels
Content-Type: application/json

{
  "id": "my-packaging",
  "description": "마이패키징"
}

### 채널 리스트 조회
GET http://localhost:3000/packaging/channels

### 채널 조회
GET http://localhost:3000/packaging/channels/my-packaging

### 채널 수정
PUT http://localhost:3000/packaging/channels/my-packaging
Content-Type: application/json

{
  "description": "설명없음"
}

### 채널 삭제
DELETE http://localhost:3000/packaging/channels/my-packaging

### 채널 앤드포인트 추가
POST http://localhost:3000/packaging/channels/my-packaging/endpoints
Content-Type: application/json

{
  "endpointId": "my-endpoint",
  "description": "마이앤드포인트"
}

### 채널 앤드포인트 리스트 조회
GET http://localhost:3000/packaging/channels/my-packaging/endpoints

### 채널 앤드포인트 조회
GET http://localhost:3000/packaging/channels/my-packaging/endpoints/my-endpoint

### 채널 앤드포인트 수정
PUT http://localhost:3000/packaging/channels/my-packaging/endpoints/my-endpoint
Content-Type: application/json

{
  "description": "마이유알엘"
}

### 채널 앤드포인트 삭제
DELETE http://localhost:3000/packaging/channels/my-packaging/endpoints/my-endpoint